from pathlib import Path

p = Path('_site/index.html')
h = p.read_text(encoding='utf-8')

old_css = '''.bt-pr-legs{display:grid;gap:9px}.bt-pr-leg{border:1px solid rgba(120,157,190,.18);background:#081c2b;border-radius:11px;padding:11px}.bt-pr-leg-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;font-size:11px}.bt-pr-leg-grid{display:grid;grid-template-columns:1.35fr 1.35fr 1.15fr .65fr .65fr;gap:8px}.bt-pr-leg input,.bt-pr-leg select{min-width:0;width:100%;border:1px solid rgba(120,157,190,.18);border-radius:7px;background:#06131f;color:#eaf3fb;padding:8px}.bt-pr-super{margin-top:7px;color:#8fa8bd;font-size:10px}'''
new_css = '''.bt-pr-legs{display:grid;border:1px solid rgba(120,157,190,.18);border-radius:11px;overflow:hidden;background:#081c2b}.bt-pr-leg-table-head,.bt-pr-leg-row{display:grid;grid-template-columns:68px minmax(180px,1.35fr) minmax(180px,1.25fr) minmax(170px,1fr) 120px;gap:8px;align-items:center;padding:9px 10px}.bt-pr-leg-table-head{background:#0b2233;border-bottom:1px solid rgba(120,157,190,.18);color:#809bb2;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.bt-pr-leg-row{border-bottom:1px solid rgba(120,157,190,.12)}.bt-pr-leg-row:last-child{border-bottom:0}.bt-pr-leg-num{font-size:11px;font-weight:800;color:#dce7f4}.bt-pr-leg-cell{min-width:0}.bt-pr-leg-cell label{display:none}.bt-pr-leg-row input,.bt-pr-leg-row select{min-width:0;width:100%;border:1px solid rgba(120,157,190,.18);border-radius:7px;background:#06131f;color:#eaf3fb;padding:8px}.bt-pr-leg-super input:placeholder-shown{color:#71889d}'''
if h.count(old_css) != 1:
    raise SystemExit(f'Expected one old Paddy leg CSS block, found {h.count(old_css)}')
h = h.replace(old_css, new_css, 1)

old_render = '''<div class="bt-pr-legs">${(p.legs||[]).map((l,i)=>`<div class="bt-pr-leg"><div class="bt-pr-leg-head"><b>Leg ${i+1}</b><span>${esc(l.sport||'')}</span></div><div class="bt-pr-leg-grid"><input data-leg="${i}" data-lkey="event" value="${esc(l.event||'')}" title="Fixture"><input data-leg="${i}" data-lkey="market" value="${esc(l.market||'')}" title="Market"><input data-leg="${i}" data-lkey="selection" value="${esc(l.selection||'')}" title="Selection"><input data-leg="${i}" data-lkey="odds" value="${esc(l.odds??'')}" title="Leg odds"><select data-leg="${i}" data-lkey="result"><option ${l.result==='Win'?'selected':''}>Win</option><option ${l.result==='Loss'?'selected':''}>Loss</option><option ${l.result==='Void'?'selected':''}>Void</option><option ${l.result==='Pending'?'selected':''}>Pending</option></select></div>${l._superSubReplacement?`<div class="bt-pr-super">Super Sub replacement: <b>${esc(l._superSubReplacement)}</b></div>`:''}</div>`).join('')}</div>'''
new_render = '''<div class="bt-pr-legs"><div class="bt-pr-leg-table-head"><span>Leg</span><span>Market</span><span>Selection</span><span>Super Sub</span><span>Result</span></div>${(p.legs||[]).map((l,i)=>`<div class="bt-pr-leg-row"><div class="bt-pr-leg-num">Leg ${i+1}</div><div class="bt-pr-leg-cell"><label>Market</label><input data-leg="${i}" data-lkey="market" value="${esc(l.market||'')}" title="Market"></div><div class="bt-pr-leg-cell"><label>Selection</label><input data-leg="${i}" data-lkey="selection" value="${esc(l.selection||'')}" title="Selection"></div><div class="bt-pr-leg-cell bt-pr-leg-super"><label>Super Sub</label><input data-leg="${i}" data-lkey="_superSubReplacement" value="${esc(l._superSubReplacement||'')}" placeholder="—" title="Super Sub replacement"></div><div class="bt-pr-leg-cell"><label>Result</label><select data-leg="${i}" data-lkey="result"><option ${l.result==='Win'?'selected':''}>Win</option><option ${l.result==='Loss'?'selected':''}>Loss</option><option ${l.result==='Void'?'selected':''}>Void</option><option ${l.result==='Pending'?'selected':''}>Pending</option></select></div></div>`).join('')}</div>'''
if h.count(old_render) != 1:
    raise SystemExit(f'Expected one old Paddy leg renderer, found {h.count(old_render)}')
h = h.replace(old_render, new_render, 1)

old_media = '''@media(max-width:800px){.bt-paddy-review-overlay{padding:0}.bt-paddy-review-shell{width:100vw;height:100vh;max-height:none;border-radius:0}.bt-pr-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.bt-pr-leg-grid{grid-template-columns:1fr}.bt-pr-wide{grid-column:span 2}.bt-pr-head,.bt-pr-foot{padding:11px}.bt-pr-body{padding:11px}}'''
new_media = '''@media(max-width:800px){.bt-paddy-review-overlay{padding:0}.bt-paddy-review-shell{width:100vw;height:100vh;max-height:none;border-radius:0}.bt-pr-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.bt-pr-leg-table-head{display:none}.bt-pr-leg-row{grid-template-columns:58px minmax(0,1fr);gap:7px 9px;align-items:start}.bt-pr-leg-num{grid-row:1 / span 4;padding-top:23px}.bt-pr-leg-cell{grid-column:2}.bt-pr-leg-cell label{display:block;margin:0 0 4px;color:#809bb2;font-size:8px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.bt-pr-wide{grid-column:span 2}.bt-pr-head,.bt-pr-foot{padding:11px}.bt-pr-body{padding:11px}}'''
if h.count(old_media) != 1:
    raise SystemExit(f'Expected one old Paddy mobile rule, found {h.count(old_media)}')
h = h.replace(old_media, new_media, 1)

p.write_text(h, encoding='utf-8')
print('Applied Paddy review leg table: Leg | Market | Selection | Super Sub | Result')
